base_url = "https://zuruh.dev"
theme = "feather"

title = "Zuruh's Blog"
description = "Yeah"
default_language = "en"

compile_sass = false
minify_html = true

build_search_index = false

generate_feeds = true

[[taxonomies]]
name = "tags"
feed = true

[markdown]
highlight_code = true
error_on_missing_highlight = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra.feather]
# hide_nav_image = false
social = { url = "https://x.com/yziadi_", display = "@yziadi_" }
timezone = "Europe/Paris"
